site_name: Moje projekty
site_author: Bogusław Bałanda
site_description: >-
    Portfolio moich projektów z Data Science i AI!

repo_name: bodekb-prog/ds_ai_portfolio
repo_url: https://github.com/bodekb-prog/ds_ai_portfolio/

theme:
  name: material
  features:
    - content.action.view
    - content.code.copy
    - content.image.zoom

plugins:
  - search
  - glightbox:
      zoomable: true

nav:
  - Strona Główna: index.md
  - Obecny projekt:
      - "Grupowanie Faktur – Inteligentny system grupowanie pozycji faktur": grupowanie_faktur/index.md
  - Poprzednie projekty:
      - "Find Friends – Inteligentny system dopasowywania użytkowników": find_friends/index.md
      - "Analiza Półmaratonu Wrocławskiego": halfmarathon/index.md
      - "Titanic": titanic/index.md
      - "Iris": iris/index.md

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences